myfirst/apps/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment')
]

myfirst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

myfirst/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone

class Article(models.Model):
    article_title = models.CharField('article name',max_length=200)
    article_text = models.TextField('article text')
    pub_date = models.DateTimeField('publication date')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_name = models.CharField('name of author', max_length=50)
    comment_text = models.TextField('text of comment', max_length=200)

    def __str__(self):
        return self.author_name

myfirst/apps/articles/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse

from .models import Article, Comment

def index(request):
    latest_articles_list = Article.objects.all()
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})

def detail(request, article_id):
    try:
        a = Article.objects.get(id = article_id)
    except:
        raise Http404("Article not found")

    latest_comments_list = a.comment_set.all()

    return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})

def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id = article_id)
    except:
        raise Http404("Article not found")

    a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])
    
    return HttpResponseRedirect(reverse('articles:detail', args = (a.id,)))

myfirst/templates/articles/detail.html
{% extends 'base.html' %}
{% block title %}
{{article.article_title}}
{% endblock %}
{% block content %}
<div class="container">
<h2>{{article.article_title}}</h2>
<p>{{article.article_text}}</p>
<em>{{article.pub_date}}</em>
<p>
{% if article.was_published_recently %}
New article
{% endif %}
</p>
<hr>
{% if latest_comments_list %}
{% for c in latest_comments_list %}
<p>
    <strong>
        {{c.author_name}}
    </strong>
    <p>{{c.comment_text}}</p>
</p>
{% endfor %}
{% else %}
<p>
Comments not found
</p>
{% endif %}

<hr>
<form action="{% url 'articles:leave_comment' article.id %}" method="POST">
{% csrf_token %}

<input type="text" required placeholder="Your name" name="name"><br>
<textarea name="text" required="" placeholder="Text of comment" cols="30" rows="10"></textarea><br>
<button type="submit">Leave comment</button>
</form>
</div>
{% endblock %}

myfirst/templates/articles/list.html
{% extends 'base.html' %}
{% block title %}
New articles
{% endblock %}
{% block content %}
{% if latest_articles_list %}
{% for a in latest_articles_list %}
<div class="container">
    <h2><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></h2>
    <p>{{a.article_text}}</p>
    <p>{{a.pub_date}}</p>
</div>
{% endfor %}
{% else %}
Articles not found
{% endif %}
{% endblock %}

myfirst/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/articles.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>